### ISSUE TITLE
Dynamic crossAxisCount based on device orientation.

### ISSUE THREAD

**Issue by efroim102** [letsar/flutter_staggered_grid_view#14]
Hi, 

I've been struggling with creating a grid layout that is dynamic and adjusts based on the device orientation.

Since with flutter's GridView you can't specify different heights for different tiles I thought you're library might do the trick.

My scenario is similar to Android's build in Contacts App, when creating a new contact (or editing one for that matter), in portrait mode the whole view is scroll-able with the user's avatar placed on top of the contact form in a top-to-bottom layout, when you switch to landscape mode however, the layout changes to a side-by-side layout with the avatar taking up the left half of the screen (full height and non scroll-able) and the contact form to the right fully scroll-able independent of the avatar to the left which stays fixed.

I thought setting the `crossAxisCount` in a `StaggeredGridView.countBuilder` based on the orientation will make it so that I can switch between having only 1 item in the cross axis (in portrait mode where there's a vertical layout) to having 2 items in the cross axis (in landscape mode where there's a horizontal layout).

Unfortunately, even though the `StaggeredGridView.countBuilder` is nested within a `OrientationBuilder` whenever I switch orientation, the layout doesn't seem to update as if the `crossAxisCount` property is not dynamic and can not be updated once set.

Is this expected behavior or am I doing something wrong? (in which case is there a workaround?)

Thanks in advance

**Comment by efroim102** [comment]
Here's the code I'm using.

```
      body: OrientationBuilder(
        builder: (context, or) {
          int cac = (or == Orientation.portrait) ? 1 : 2;
          return StaggeredGridView.countBuilder(
            controller: _listViewScrollController,
            itemBuilder: (BuildContext context, int index){
              return _view[index];
            },
            itemCount: 2,
            crossAxisCount: cac,
            staggeredTileBuilder: (int index) {
              return StaggeredTile.fit(cac);
            },
            scrollDirection: Axis.vertical,
          );
        },
      )
```

**Comment by letsar** [comment]
Hi.

What you are trying to do with the OrientationBuilder should work, and in fact, I've just tested it and it works, so I don't understand it doesn't in your case 😕 .

But I don't think `StaggeredGridView` is the right solution to handle what you're trying to do: When the app is in landscape mode, the contact app only allows you to scroll the fields area. If you use `StaggeredGridView` to handle your layout, the avatar cell will scroll along with fields area.

I think I have a better solution for your case, if I understood correctly and what you want is something like this:
![orientation_test](https://user-images.githubusercontent.com/9378033/43043471-bbf0f5ba-8d94-11e8-8f2d-d600e12d3106.gif)

Do you mind to post a question about how to create the layout of the scenario you want on StackOverflow, and post me the link here? So that I can answer it there, and it will be useful for other people.

**Comment by efroim102** [comment]
Sure, Here you go: https://stackoverflow.com/questions/51463355/how-do-i-create-a-dynamic-flutter-grid-layout-based-on-device-orientation-when-t

Thanks so much, I'm sure I'll get some hate on SO for being too generic, I might update the question at a later point if that's the case. Thanks again.

**Comment by letsar** [comment]
Thanks, I posted my answer.
