### ISSUE TITLE
How to fit extent for cross axis?

### ISSUE THREAD

**Issue by proninyaroslav** [letsar/flutter_staggered_grid_view#204]
I want to do something like this:

![](https://user-images.githubusercontent.com/7840559/134816887-84cc1491-6721-47fb-a3de-799ebcd64b33.png)

Let's say the cross axis has a size of 5 cells, but depending on the image orientation (portrait or landscape), it can take either 1 cell (portrait) or 2 cells (landscape). The dimensions of the image are unknown before I load them into the `Image` widget. Is it possible to do something similar to `StaggeredTile.fit` or` StaggeredTile.extent` for the cross axis?

**Comment by proninyaroslav** [comment]
Or, maybe, add the ability to rebuild `StaggeredTile` without rebuilding the entire list.

**Comment by letsar** [comment]
Can you test with the latest 0.5.0 preview? https://pub.dev/packages/flutter_staggered_grid_view/versions/0.5.0-dev.1

**Comment by proninyaroslav** [comment]
@letsar 
Which widget is the most suitable for cross axis extent/fit? Like a `MasonryGridView`, but cross axis only.

**Comment by letsar** [comment]
You can use the `MasonryGridView` with a `scrollDirection` set to `Axis.horizontal` but it will scroll horizontally. Which is maybe not what you want.
Since you don't know in advance, or are you sure each row will be filled? Is it possible to have 5 landscape images in a row (the expression 😅)? It it's the case, how do you handle empty areas?
If a repeatable pattern can be inferred, maybe the quilted grid would be more appropriate. I need to have more information to know what is the best way to handle this.

**Comment by letsar** [comment]
This thread has been closed since there has not been any response for a while. If you are still experiencing a similar issue, please open a new bug.
