### ISSUE TITLE
how to convert StaggeredGridView.countBuilder in new version?

### ISSUE THREAD

**Issue by XOneto9** [letsar/flutter_staggered_grid_view#233]
Hi, 
I'm read issues related to StaggeredGridView.countBuilder error after applying new version #217  #219. 
But, It is not enough to solving problem for me. So, one more again ask this.

How to convert to new version with compatible StaggeredGridView.countBuilder Widget?

My app need to make builder for different width each index cell, and count with scrollable.
Could you let me know how to this on new version
Thanks

**Comment by sarafinmahtab** [comment]
Looks like the new update is a wasted version. I need to use the old version now.

**Comment by letsar** [comment]
@sarafinmahtab thanks for the comment, always a pleasure to spend my free time working on libs and get these kind of comments!
I didn't wrote a full migration guide because it depends on what you want to do, but there is a wiki to explain all the different kind of layout this lib now offers: https://github.com/letsar/flutter_staggered_grid_view/wiki
Feel free to read it.

**Comment by iampato** [comment]
Its hard to understand the wiki
